const MISSING_MONSTER_DETAILS = [
  "Svirfneblin",
  "Cave Bear",
  "Specter (poltergeist)",
  "Will-o-wisp",
  "Quaggoth Thonot",
  "Incubus",
  "Lizard King/Queen",
  "Young Brass Dragon",
  "Young White Dragon",
  "Young Black Dragon",
  "Young Copper Dragon",
  "Mind Flayer Arcanist",
  "Young Bronze Dragon",
  "Young Green Dragon",
  "Young Blue Dragon",
  "Young Silver Dragon",
  "Young Gold Dragon",
  "Young Red Dragon",
  "Adult Brass Dragon",
  "Adult White Dragon",
  "Young Red Shadow Dragon",
  "Adult Black Dragon",
  "Adult Copper Dragon",
  "Adult Bronze Dragon",
  "Adult Green Dragon",
  "Vampire (spellcaster)",
  "Vampire (warrior)",
  "Adult Blue Dragon",
  "Adult Silver Dragon",
  "Adult Blue Dracolich",
  "Adult Gold Dragon",
  "Adult Red Dragon",
  "Ancient Brass Dragon",
  "Ancient White Dragon",
  "Ancient Black Dragon",
  "Ancient Copper Dragon",
  "Ancient Bronze Dragon",
  "Ancient Green Dragon",
  "Ancient Blue Dragon",
  "Ancient Silver Dragon",
  "Ancient Gold Dragon",
  "Ancient Red Dragon",
];
