export const MONSTERS_BY_BIOME = {
  acuatic: [
    'Aboleth',
    'Adult Bronze Dragon',
    'Ancient Bronze Dragon',
    'Bronze Dragon Wyrmling',
    'Chuul',
    'Dragon Turtle',
    'Giant Octopus',
    'Giant Sea Horse',
    'Giant Shark',
    'Hunter Shark',
    'Killer Whale',
    'Merfolk',
    'Merrow',
    'Octopus',
    'Plesiosaurus',
    'Quipper',
    'Reef Shark',
    'Sahuagin',
    'Sahuagin Baron',
    'Sahuagin Priestess',
    'Sea Hag',
    'Sea Horse',
    'Swarm of Quippers',
    'Water Weird',
    'Young Bronze Dragon',
  ],
  desert: [
    'Adult Blue Dragon',
    'Adult Brass Dragon',
    'Ancient Blue Dragon',
    'Ancient Brass Dragon',
    'Blue Dragon Wyrmling',
    'Brass Dragon Wyrmling',
    'Lamia',
    'Thri-kreen',
    'Young Blue Dragon',
    'Young Brass Dragon',
  ],
  forest: [
    'Adult Green Dragon',
    'Ancient Green Dragon',
    'Dryad',
    'Green Dragon Wyrmling',
    'Treant',
    'Young Green Dragon',
  ],
  grassland: ['Lion'],
  jungle: ['Lizard King/Queen', 'Lizardfolk', 'Lizardfolk Shaman'],
  mountains: [
    'Adult Copper Dragon',
    'Adult Red Dragon',
    'Adult Silver Dragon',
    'Ancient Copper Dragon',
    'Ancient Red Dragon',
    'Ancient Silver Dragon',
    'Copper Dragon Wyrmling',
    'Peryton',
    'Red Dragon Wyrmling',
    'Silver Dragon Wyrmling',
    'Young Copper Dragon',
    'Young Red Dragon',
    'Young Silver Dragon',
  ],
  swamp: [
    'Adult Black Dragon',
    'Ancient Black Dragon',
    'Black Dragon Wyrmling',
    'Bullywug',
    'Young Black Dragon',
  ],
  tundra: [
    'Abominable Yeti',
    'Adult White Dragon',
    'Ancient White Dragon',
    'Polar Bear',
    'Remorhaz',
    'White Dragon Wyrmling',
    'Winter Wolf',
    'Yeti',
    'Young Remorhaz',
    'Young White Dragon',
  ],
  undergrown: [
    'Ankheg',
    'Black Pudding',
    'Cloaker',
    'Darkmantle',
    'Deep Gnome (Svirfneblin)',
    'Drider',
    'Drow',
    'Drow Elite Warrior',
    'Drow Mage',
    'Drow Priestess of Lolth',
    'Duergar',
    'Flumph',
    'Fomorian',
    'Galeb Duhr',
    'Gas Spore',
    'Gelatinous Cube',
    'Gray Ooze',
    'Grell',
    'Grick',
    'Grick Alpha',
    'Grimlock',
    'Hook Horror',
    'Kuo-toa',
    'Kuo-toa Archpriest',
    'Kuo-toa Whip',
    'Mind Flayer',
    'Myconid Adult',
    'Myconid Sovereign',
    'Myconid Sprout',
    'Nothic',
    'Ochre Jelly',
    'Piercer',
    'Quaggoth  ',
    'Quaggoth Spore Servant',
    'Roper',
    'Shrieker',
    'Troglodyte',
    'Umber Hulk',
    'Violet Fungus',
  ]
};
