export const MONSTER_IMAGES = {
  Aarakocra: 'https://www.aidedd.org/dnd/images/aarakocra.jpg',
  Aboleth: 'https://www.aidedd.org/dnd/images/aboleth.jpg',
  'Abominable Yeti': 'https://www.aidedd.org/dnd/images/yeti.jpg',
  'Adult Black Dragon': 'https://www.aidedd.org/dnd/images/black-dragon.jpg',
  'Adult Blue Dracolich': 'https://www.aidedd.org/dnd/images/dracolich.jpg',
  'Adult Blue Dragon': 'https://www.aidedd.org/dnd/images/blue-dragon.jpg',
  'Adult Brass Dragon': 'https://www.aidedd.org/dnd/images/brass-dragon.jpg',
  'Adult Bronze Dragon': 'https://www.aidedd.org/dnd/images/bronze-dragon.jpg',
  'Adult Copper Dragon': 'https://www.aidedd.org/dnd/images/copper-dragon.jpg',
  'Adult Gold Dragon': 'https://www.aidedd.org/dnd/images/gold-dragon.jpg',
  'Adult Green Dragon': 'https://www.aidedd.org/dnd/images/green-dragon.jpg',
  'Adult Red Dragon': 'https://www.aidedd.org/dnd/images/red-dragon.jpg',
  'Adult Silver Dragon': 'https://www.aidedd.org/dnd/images/silver-dragon.jpg',
  'Adult White Dragon': 'https://www.aidedd.org/dnd/images/white-dragon.jpg',
  'Air Elemental': 'https://www.aidedd.org/dnd/images/air-elemental.jpg',
  'Ancient Black Dragon': 'https://www.aidedd.org/dnd/images/black-dragon.jpg',
  'Ancient Blue Dragon': 'https://www.aidedd.org/dnd/images/blue-dragon.jpg',
  'Ancient Brass Dragon': 'https://www.aidedd.org/dnd/images/brass-dragon.jpg',
  'Ancient Bronze Dragon':
    'https://www.aidedd.org/dnd/images/bronze-dragon.jpg',
  'Ancient Copper Dragon':
    'https://www.aidedd.org/dnd/images/copper-dragon.jpg',
  'Ancient Gold Dragon': 'https://www.aidedd.org/dnd/images/gold-dragon.jpg',
  'Ancient Green Dragon': 'https://www.aidedd.org/dnd/images/green-dragon.jpg',
  'Ancient Red Dragon': 'https://www.aidedd.org/dnd/images/red-dragon.jpg',
  'Ancient Silver Dragon':
    'https://www.aidedd.org/dnd/images/silver-dragon.jpg',
  'Ancient White Dragon': 'https://www.aidedd.org/dnd/images/white-dragon.jpg',
  Androsphinx: 'https://www.aidedd.org/dnd/images/androsphinx.jpg',
  'Animated Armor': 'https://www.aidedd.org/dnd/images/animated-armor.jpg',
  Ankheg: 'https://www.aidedd.org/dnd/images/ankheg.jpg',
  Ankylosaurus: 'https://www.aidedd.org/dnd/images/ankylosaurus.jpg',
  Arcanaloth: 'https://www.aidedd.org/dnd/images/arcanaloth.jpg',
  Archmage: 'https://www.aidedd.org/dnd/images/archmage.jpg',
  'Axe Beak': 'https://www.aidedd.org/dnd/images/axe-beak.jpg',
  Azer: 'https://www.aidedd.org/dnd/images/azer.jpg',
  Badger: 'https://www.aidedd.org/dnd/images/badger.jpg',
  Balor: 'https://www.aidedd.org/dnd/images/demon-balor.jpg',
  Bulezau: 'https://www.aidedd.org/dnd/images/bulezau.jpg',
  'Bandit Captain': 'https://www.aidedd.org/dnd/images/bandit-captain.jpg',
  Banshee: 'https://www.aidedd.org/dnd/images/banshee.jpg',
  'Barbed Devil': 'https://www.aidedd.org/dnd/images/barbed-devil.jpg',
  Barlgura: 'https://www.aidedd.org/dnd/images/barlgura.jpg',
  Basilisk: 'https://www.aidedd.org/dnd/images/basilisk.jpg',
  'Bearded Devil': 'https://www.aidedd.org/dnd/images/bearded-devil.jpg',
  Behir: 'https://www.aidedd.org/dnd/images/behir.jpg',
  Beholder: 'https://www.aidedd.org/dnd/images/beholder.jpg',
  'Beholder Zombie': 'https://www.aidedd.org/dnd/images/beholder-zombie.jpg',
  'Black Pudding': 'https://www.aidedd.org/dnd/images/black-pudding.jpg',
  'Blink Dog': 'https://www.aidedd.org/dnd/images/blink-dog.jpg',
  'Blue Slaad': 'https://www.aidedd.org/dnd/images/blue-slaad.jpg',
  'Bone Devil': 'https://www.aidedd.org/dnd/images/bone-devil.jpg',
  'Bone Naga': 'https://www.aidedd.org/dnd/images/bone-naga.jpg',
  Bugbear: 'https://www.aidedd.org/dnd/images/bugbear.jpg',
  'Bugbear Chief': 'https://www.aidedd.org/dnd/images/bugbear.jpg',
  Bulette: 'https://www.aidedd.org/dnd/images/bulette.jpg',
  Bullywug: 'https://www.aidedd.org/dnd/images/bullywug.jpg',
  Cambion: 'https://www.aidedd.org/dnd/images/cambion.jpg',
  'Carrion Crawler': 'https://www.aidedd.org/dnd/images/carrion-crawler.jpg',
  Centaur: 'https://www.aidedd.org/dnd/images/centaur.jpg',
  'Chain Devil': 'https://www.aidedd.org/dnd/images/chain-devil.jpg',
  Chasme: 'https://www.aidedd.org/dnd/images/demon-chasme.jpg',
  Chimera: 'https://www.aidedd.org/dnd/images/chimera.jpg',
  Chuul: 'https://www.aidedd.org/dnd/images/chuul.jpg',
  'Clay Golem': 'https://www.aidedd.org/dnd/images/clay-golem.jpg',
  Cloaker: 'https://www.aidedd.org/dnd/images/cloaker.jpg',
  'Cloud Giant': 'https://www.aidedd.org/dnd/images/cloud-giant.jpg',
  Cockatrice: 'https://www.aidedd.org/dnd/images/cockatrice.jpg',
  Couatl: 'https://www.aidedd.org/dnd/images/couatl.jpg',
  'Crawling Claw': 'https://www.aidedd.org/dnd/images/crawling-claw.jpg',
  Crocodile: 'https://www.aidedd.org/dnd/images/crocodile.jpg',
  'Cult Fanatic': 'https://www.aidedd.org/dnd/images/cult-fanatic.jpg',
  Cyclops: 'https://www.aidedd.org/dnd/images/cyclops.jpg',
  Dao: 'https://www.aidedd.org/dnd/images/dao.jpg',
  Darkmantle: 'https://www.aidedd.org/dnd/images/darkmantle.jpg',
  'Death Dog': 'https://www.aidedd.org/dnd/images/death-dog.jpg',
  'Death Knight': 'https://www.aidedd.org/dnd/images/death-knight.jpg',
  'Death Slaad': 'https://www.aidedd.org/dnd/images/death-slaad.jpg',
  'Death Tyrant': 'https://www.aidedd.org/dnd/images/death-tyrant.jpg',
  'Deep Gnome (Svirfneblin)':
    'https://www.aidedd.org/dnd/images/deep-gnome.jpg',
  Demilich: 'https://www.aidedd.org/dnd/images/demilich.jpg',
  Deva: 'https://www.aidedd.org/dnd/images/deva.jpg',
  'Dire Wolf': 'https://www.aidedd.org/dnd/images/dire-wolf.jpg',
  'Displacer Beast': 'https://www.aidedd.org/dnd/images/displacer-beast.jpg',
  Djinni: 'https://www.aidedd.org/dnd/images/djinni.jpg',
  Doppelganger: 'https://www.aidedd.org/dnd/images/doppelganger.jpg',
  'Dragon Turtle': 'https://www.aidedd.org/dnd/images/dragon-turtle.jpg',
  Dretch: 'https://www.aidedd.org/dnd/images/demon-dretch.jpg',
  Drider: 'https://www.aidedd.org/dnd/images/drider.jpg',
  Drow: 'https://www.aidedd.org/dnd/images/drow.jpg',
  'Drow Mage': 'https://www.aidedd.org/dnd/images/drow-mage.jpg',
  'Drow Priestess of Lolth': 'https://www.aidedd.org/dnd/images/drow.jpg',
  Druid: 'https://www.aidedd.org/dnd/images/druid.jpg',
  Dryad: 'https://www.aidedd.org/dnd/images/dryad.jpg',
  Duergar: 'https://www.aidedd.org/dnd/images/duergar.jpg',
  Duodrone: 'https://www.aidedd.org/dnd/images/duodrone.jpg',
  'Dust Mephit': 'https://www.aidedd.org/dnd/images/dust-mephit.jpg',
  Eagle: 'https://www.aidedd.org/dnd/images/eagle.jpg',
  'Earth Elemental': 'https://www.aidedd.org/dnd/images/earth-elemental.jpg',
  Efreeti: 'https://www.aidedd.org/dnd/images/efreeti.jpg',
  Empyrean: 'https://www.aidedd.org/dnd/images/empyrean.jpg',
  Erinyes: 'https://www.aidedd.org/dnd/images/erinyes.jpg',
  Ettercap: 'https://www.aidedd.org/dnd/images/ettercap.jpg',
  Ettin: 'https://www.aidedd.org/dnd/images/ettin.jpg',
  'Faerie Dragon': 'https://www.aidedd.org/dnd/images/faerie-dragon.jpg',
  'Fire Elemental': 'https://www.aidedd.org/dnd/images/fire-elemental.jpg',
  'Fire Giant': 'https://www.aidedd.org/dnd/images/fire-giant.jpg',
  'Fire Snake': 'https://www.aidedd.org/dnd/images/fire-snake.jpg',
  Flameskull: 'https://www.aidedd.org/dnd/images/flameskull.jpg',
  'Flesh Golem': 'https://www.aidedd.org/dnd/images/flesh-golem.jpg',
  Flumph: 'https://www.aidedd.org/dnd/images/flumph.jpg',
  'Flying Snake': 'https://www.aidedd.org/dnd/images/flying-snake.jpg',
  'Flying Sword': 'https://www.aidedd.org/dnd/images/flying-sword.jpg',
  Fomorian: 'https://www.aidedd.org/dnd/images/fomorian.jpg',
  Frog: 'https://www.aidedd.org/dnd/images/frog.jpg',
  'Frost Giant': 'https://www.aidedd.org/dnd/images/frost-giant.jpg',
  'Galeb Duhr': 'https://www.aidedd.org/dnd/images/galeb-duhr.jpg',
  Gargoyle: 'https://www.aidedd.org/dnd/images/gargoyle.jpg',
  'Gelatinous Cube': 'https://www.aidedd.org/dnd/images/gelatinous-cube.jpg',
  Ghast: 'https://www.aidedd.org/dnd/images/ghast.jpg',
  Ghost: 'https://www.aidedd.org/dnd/images/ghost.jpg',
  Ghoul: 'https://www.aidedd.org/dnd/images/ghoul.jpg',
  'Giant Fire Beetle':
    'https://www.aidedd.org/dnd/images/giant-fire-beetle.jpg',
  'Giant Octopus': 'https://www.aidedd.org/dnd/images/octopus.jpg',
  'Giant Spider': 'https://www.aidedd.org/dnd/images/giant-spider.jpg',
  'Gibbering Mouther':
    'https://www.aidedd.org/dnd/images/gibbering-mouther.jpg',
  'Githyanki Knight': 'https://www.aidedd.org/dnd/images/githyanki.jpg',
  'Githyanki Warrior': 'https://www.aidedd.org/dnd/images/githyanki.jpg',
  'Githzerai Monk': 'https://www.aidedd.org/dnd/images/githzerai.jpg',
  'Githzerai Zerth': 'https://www.aidedd.org/dnd/images/githzerai.jpg',
  Glabrezu: 'https://www.aidedd.org/dnd/images/demon-glabrezu.jpg',
  Gnoll: 'https://www.aidedd.org/dnd/images/gnoll.jpg',
  Goblin: 'https://www.aidedd.org/dnd/images/goblin.jpg',
  'Goblin Boss': 'https://www.aidedd.org/dnd/images/goblin.jpg',
  Gorgon: 'https://www.aidedd.org/dnd/images/gorgon.jpg',
  Goristro: 'https://www.aidedd.org/dnd/images/demon-goristro.jpg',
  'Gray Ooze': 'https://www.aidedd.org/dnd/images/gray-ooze.jpg',
  'Gray Slaad': 'https://www.aidedd.org/dnd/images/gray-slaad.jpg',
  'Green Hag': 'https://www.aidedd.org/dnd/images/green-hag.jpg',
  'Green Slaad': 'https://www.aidedd.org/dnd/images/green-slaad.jpg',
  Grell: 'https://www.aidedd.org/dnd/images/grell.jpg',
  Grick: 'https://www.aidedd.org/dnd/images/grick.jpg',
  Griffon: 'https://www.aidedd.org/dnd/images/griffon.jpg',
  Grimlock: 'https://www.aidedd.org/dnd/images/grimlock.jpg',
  'Guardian Naga': 'https://www.aidedd.org/dnd/images/guardian-naga.jpg',
  Gynosphinx: 'https://www.aidedd.org/dnd/images/gynosphinx.jpg',
  'Half-Ogre': 'https://www.aidedd.org/dnd/images/half-ogre.jpg',
  'Half-Red Dragon Veteran':
    'https://www.aidedd.org/dnd/images/half-red-dragon.jpg',
  Harpy: 'https://www.aidedd.org/dnd/images/harpy.jpg',
  Hawk: 'https://www.aidedd.org/dnd/images/hawk.jpg',
  'Hell Hound': 'https://www.aidedd.org/dnd/images/hell-hound.jpg',
  'Helmed Horror': 'https://www.aidedd.org/dnd/images/helmed-horror.jpg',
  Hezrou: 'https://www.aidedd.org/dnd/images/demon-hezrou.jpg',
  'Hill Giant': 'https://www.aidedd.org/dnd/images/hill-giant.jpg',
  Hippogriff: 'https://www.aidedd.org/dnd/images/hippogriff.jpg',
  Hobgoblin: 'https://www.aidedd.org/dnd/images/hobgoblin.jpg',
  'Hobgoblin Warlord': 'https://www.aidedd.org/dnd/images/hobgoblin.jpg',
  'Hobgoblin Devastator': 'https://www.aidedd.org/dnd/images/hobgoblin-devastator.jpg',
  'Hobgoblin Captain': 'https://www.aidedd.org/dnd/images/hobgoblin.jpg',
  Homunculus: 'https://www.aidedd.org/dnd/images/homunculus.jpg',
  'Hook Horror': 'https://www.aidedd.org/dnd/images/hook-horror.jpg',
  'Horned Devil': 'https://www.aidedd.org/dnd/images/horned-devil.jpg',
  Hydra: 'https://www.aidedd.org/dnd/images/hydra.jpg',
  Hyena: 'https://www.aidedd.org/dnd/images/hyena.jpg',
  'Ice Devil': 'https://www.aidedd.org/dnd/images/ice-devil.jpg',
  'Ice Mephit': 'https://www.aidedd.org/dnd/images/ice-mephit.jpg',
  Imp: 'https://www.aidedd.org/dnd/images/imp.jpg',
  'Intellect Devourer':
    'https://www.aidedd.org/dnd/images/intellect-devorer.jpg',
  'Invisible Stalker':
    'https://www.aidedd.org/dnd/images/invisible-stalker.jpg',
  'Iron Golem': 'https://www.aidedd.org/dnd/images/iron-golem.jpg',
  Jackalwere: 'https://www.aidedd.org/dnd/images/jackalwere.jpg',
  Kenku: 'https://www.aidedd.org/dnd/images/kenku.jpg',
  Kobold: 'https://www.aidedd.org/dnd/images/kobold.jpg',
  Kraken: 'https://www.aidedd.org/dnd/images/kraken.jpg',
  'Kuo-toa': 'https://www.aidedd.org/dnd/images/kuo-toa.jpg',
  'Kuo-toa Archpriest':
    'https://www.aidedd.org/dnd/images/kuo-toa-archpriest.jpg',
  'Kuo-toa Whip': 'https://www.aidedd.org/dnd/images/kuo-toa-whip.jpg',
  Lamia: 'https://www.aidedd.org/dnd/images/lamia.jpg',
  Lemure: 'https://www.aidedd.org/dnd/images/lemure.jpg',
  Lich: 'https://www.aidedd.org/dnd/images/lich.jpg',
  Lizardfolk: 'https://www.aidedd.org/dnd/images/lizardfolk.jpg',
  'Magma Mephit': 'https://www.aidedd.org/dnd/images/magma-mephit.jpg',
  Magmin: 'https://www.aidedd.org/dnd/images/magmin.jpg',
  Manes: 'https://www.aidedd.org/dnd/images/demon-manes.jpg',
  Manticore: 'https://www.aidedd.org/dnd/images/manticore.jpg',
  Marid: 'https://www.aidedd.org/dnd/images/marid.jpg',
  Marilith: 'https://www.aidedd.org/dnd/images/demon-marilith.jpg',
  Mastiff: 'https://www.aidedd.org/dnd/images/mastiff.jpg',
  Medusa: 'https://www.aidedd.org/dnd/images/medusa.jpg',
  Merfolk: 'https://www.aidedd.org/dnd/images/merfolk.jpg',
  Merrow: 'https://www.aidedd.org/dnd/images/merrow.jpg',
  Mezzoloth: 'https://www.aidedd.org/dnd/images/mezzoloth.jpg',
  Mimic: 'https://www.aidedd.org/dnd/images/mimic.jpg',
  'Mind Flayer': 'https://www.aidedd.org/dnd/images/mind-flayer.jpg',
  Minotaur: 'https://www.aidedd.org/dnd/images/minotaur.jpg',
  'Minotaur Skeleton':
    'https://www.aidedd.org/dnd/images/minotaur-skeleton.jpg',
  Monodrone: 'https://www.aidedd.org/dnd/images/monodrone.jpg',
  'Mud Mephit': 'https://www.aidedd.org/dnd/images/mud-mephit.jpg',
  Mummy: 'https://www.aidedd.org/dnd/images/mummy.jpg',
  'Mummy Lord': 'https://www.aidedd.org/dnd/images/mummy-lord.jpg',
  'Myconid adult': 'https://www.aidedd.org/dnd/images/myconid.jpg',
  Nalfeshnee: 'https://www.aidedd.org/dnd/images/demon-nalfeshnee.jpg',
  'Needle Blight': 'https://www.aidedd.org/dnd/images/blight.jpg',
  'Night Hag': 'https://www.aidedd.org/dnd/images/night-hag.jpg',
  Nightmare: 'https://www.aidedd.org/dnd/images/nightmare.jpg',
  Noble: 'https://www.aidedd.org/dnd/images/noble.jpg',
  Nothic: 'https://www.aidedd.org/dnd/images/nothic.jpg',
  Nycaloth: 'https://www.aidedd.org/dnd/images/nycaloth.jpg',
  'Ochre Jelly': 'https://www.aidedd.org/dnd/images/ochre-jelly.jpg',
  Ogre: 'https://www.aidedd.org/dnd/images/ogre.jpg',
  'Ogre Zombie': 'https://www.aidedd.org/dnd/images/ogre-zombie.jpg',
  Oni: 'https://www.aidedd.org/dnd/images/oni.jpg',
  Orc: 'https://www.aidedd.org/dnd/images/orc.jpg',
  'Orc War Chief': 'https://www.aidedd.org/dnd/images/orc.jpg',
  Orog: 'https://www.aidedd.org/dnd/images/orog.jpg',
  Otyugh: 'https://www.aidedd.org/dnd/images/otyugh.jpg',
  Owl: 'https://www.aidedd.org/dnd/images/owl.jpg',
  Owlbear: 'https://www.aidedd.org/dnd/images/owlbear.jpg',
  Pegasus: 'https://www.aidedd.org/dnd/images/pegasus.jpg',
  Pentadrone: 'https://www.aidedd.org/dnd/images/pentadrone.jpg',
  Peryton: 'https://www.aidedd.org/dnd/images/peryton.jpg',
  'Phase Spider': 'https://www.aidedd.org/dnd/images/phase-spider.jpg',
  Piercer: 'https://www.aidedd.org/dnd/images/piercer.jpg',
  'Pit Fiend': 'https://www.aidedd.org/dnd/images/pit-fiend.jpg',
  Pixie: 'https://www.aidedd.org/dnd/images/pixie.jpg',
  Planetar: 'https://www.aidedd.org/dnd/images/planetar.jpg',
  Plesiosaurus: 'https://www.aidedd.org/dnd/images/plesiosaurus.jpg',
  Pseudodragon: 'https://www.aidedd.org/dnd/images/pseudodragon.jpg',
  'Purple Worm': 'https://www.aidedd.org/dnd/images/purple-worm.jpg',
  Quadrone: 'https://www.aidedd.org/dnd/images/quadrone.jpg',
  Quaggoth: 'https://www.aidedd.org/dnd/images/quaggoth.jpg',
  Quasit: 'https://www.aidedd.org/dnd/images/quasit.jpg',
  Quipper: 'https://www.aidedd.org/dnd/images/quipper.jpg',
  Rakshasa: 'https://www.aidedd.org/dnd/images/rakshasa.jpg',
  Rat: 'https://www.aidedd.org/dnd/images/rat.jpg',
  Raven: 'https://www.aidedd.org/dnd/images/raven.jpg',
  'Red Slaad': 'https://www.aidedd.org/dnd/images/red-slaad.jpg',
  Remorhaz: 'https://www.aidedd.org/dnd/images/remorhaz.jpg',
  'Riding Horse': 'https://www.aidedd.org/dnd/images/horse.jpg',
  Roc: 'https://www.aidedd.org/dnd/images/roc.jpg',
  Roper: 'https://www.aidedd.org/dnd/images/roper.jpg',
  'Rug of Smothering': 'https://www.aidedd.org/dnd/images/rug-smothering.jpg',
  'Rust Monster': 'https://www.aidedd.org/dnd/images/rust-monster.jpg',
  Sahuagin: 'https://www.aidedd.org/dnd/images/sahuagin.jpg',
  'Sahuagin Baron': 'https://www.aidedd.org/dnd/images/sahuagin-baron.jpg',
  Salamander: 'https://www.aidedd.org/dnd/images/salamander.jpg',
  Satyr: 'https://www.aidedd.org/dnd/images/satyr.jpg',
  Scarecrow: 'https://www.aidedd.org/dnd/images/scarecrow.jpg',
  Scout: 'https://www.aidedd.org/dnd/images/scout.jpg',
  'Sea Hag': 'https://www.aidedd.org/dnd/images/sea-hag.jpg',
  Shadow: 'https://www.aidedd.org/dnd/images/shadow.jpg',
  'Shadow Demon': 'https://www.aidedd.org/dnd/images/shadow-demon.jpg',
  'Shambling Mound': 'https://www.aidedd.org/dnd/images/shambling-mound.jpg',
  'Shield Guardian': 'https://www.aidedd.org/dnd/images/shield-guardian.jpg',
  Shrieker: 'https://www.aidedd.org/dnd/images/shrieker.jpg',
  Skeleton: 'https://www.aidedd.org/dnd/images/skeleton.jpg',
  'Smoke Mephit': 'https://www.aidedd.org/dnd/images/smoke-mephit.jpg',
  Solar: 'https://www.aidedd.org/dnd/images/solar.jpg',
  Spectator: 'https://www.aidedd.org/dnd/images/spectator.jpg',
  Specter: 'https://www.aidedd.org/dnd/images/specter.jpg',
  Spider: 'https://www.aidedd.org/dnd/images/spider.jpg',
  'Spined Devil': 'https://www.aidedd.org/dnd/images/spined-devil.jpg',
  'Spirit Naga': 'https://www.aidedd.org/dnd/images/spirit-naga.jpg',
  Sprite: 'https://www.aidedd.org/dnd/images/sprite.jpg',
  'Steam Mephit': 'https://www.aidedd.org/dnd/images/steam-mephit.jpg',
  Stirge: 'https://www.aidedd.org/dnd/images/stirge.jpg',
  'Stone Giant': 'https://www.aidedd.org/dnd/images/stone-giant.jpg',
  'Stone Golem': 'https://www.aidedd.org/dnd/images/stone-golem.jpg',
  'Storm Giant': 'https://www.aidedd.org/dnd/images/storm-giant.jpg',
  Succubus: 'https://www.aidedd.org/dnd/images/succubus.jpg',
  'Swarm of Bats': 'https://www.aidedd.org/dnd/images/swarm-bats.jpg',
  Tarrasque: 'https://www.aidedd.org/dnd/images/tarrasque.jpg',
  'Thri-kreen': 'https://www.aidedd.org/dnd/images/thri-kreen.jpg',
  Thug: 'https://www.aidedd.org/dnd/images/thug.jpg',
  Treant: 'https://www.aidedd.org/dnd/images/treant.jpg',
  Triceratops: 'https://www.aidedd.org/dnd/images/triceratops.jpg',
  Tridrone: 'https://www.aidedd.org/dnd/images/tridrone.jpg',
  Troglodyte: 'https://www.aidedd.org/dnd/images/troglodyte.jpg',
  Troll: 'https://www.aidedd.org/dnd/images/troll.jpg',
  'Twig Blight': 'https://www.aidedd.org/dnd/images/blight.jpg',
  'Tyrannosaurus Rex':
    'https://www.aidedd.org/dnd/images/tyrannosaurus-rex.jpg',
  Ultroloth: 'https://www.aidedd.org/dnd/images/ultroloth.jpg',
  'Umber Hulk': 'https://www.aidedd.org/dnd/images/umber-hulk.jpg',
  Unicorn: 'https://www.aidedd.org/dnd/images/unicorn.jpg',
  Vampire: 'https://www.aidedd.org/dnd/images/vampire.jpg',
  'Vampire Spawn': 'https://www.aidedd.org/dnd/images/vampire-spawn.jpg',
  'Vine Blight': 'https://www.aidedd.org/dnd/images/blight.jpg',
  'Violet Fungus': 'https://www.aidedd.org/dnd/images/violet-fungus.jpg',
  Vrock: 'https://www.aidedd.org/dnd/images/demon-vrock.jpg',
  'Water Elemental': 'https://www.aidedd.org/dnd/images/water-elemental.jpg',
  'Water Weird': 'https://www.aidedd.org/dnd/images/water-weird.jpg',
  Werebear: 'https://www.aidedd.org/dnd/images/wereBear.jpg',
  Wereboar: 'https://www.aidedd.org/dnd/images/wereBoar.jpg',
  Wererat: 'https://www.aidedd.org/dnd/images/wereRat.jpg',
  Weretiger: 'https://www.aidedd.org/dnd/images/wereTiger.jpg',
  Werewolf: 'https://www.aidedd.org/dnd/images/wereWolf.jpg',
  Wight: 'https://www.aidedd.org/dnd/images/wight.jpg',
  "Will-o'-Wisp": 'https://www.aidedd.org/dnd/images/will-o-wisp.jpg',
  'Winged Kobold': 'https://www.aidedd.org/dnd/images/winged-kobold.jpg',
  'Winter Wolf': 'https://www.aidedd.org/dnd/images/winter-wolf.jpg',
  Wolf: 'https://www.aidedd.org/dnd/images/dire-wolf.jpg',
  Worg: 'https://www.aidedd.org/dnd/images/worg.jpg',
  Wraith: 'https://www.aidedd.org/dnd/images/wraith.jpg',
  Wyvern: 'https://www.aidedd.org/dnd/images/wyvern.jpg',
  Xorn: 'https://www.aidedd.org/dnd/images/xorn.jpg',
  Yeti: 'https://www.aidedd.org/dnd/images/yeti.jpg',
  Yochlol: 'https://www.aidedd.org/dnd/images/demon-yochlol.jpg',
  'Young Black Dragon': 'https://www.aidedd.org/dnd/images/black-dragon.jpg',
  'Young Blue Dragon': 'https://www.aidedd.org/dnd/images/blue-dragon.jpg',
  'Young Brass Dragon': 'https://www.aidedd.org/dnd/images/brass-dragon.jpg',
  'Young Bronze Dragon': 'https://www.aidedd.org/dnd/images/bronze-dragon.jpg',
  'Young Copper Dragon': 'https://www.aidedd.org/dnd/images/copper-dragon.jpg',
  'Young Gold Dragon': 'https://www.aidedd.org/dnd/images/gold-dragon.jpg',
  'Young Green Dragon': 'https://www.aidedd.org/dnd/images/green-dragon.jpg',
  'Young Red Dragon': 'https://www.aidedd.org/dnd/images/red-dragon.jpg',
  'Young Silver Dragon': 'https://www.aidedd.org/dnd/images/silver-dragon.jpg',
  'Young White Dragon': 'https://www.aidedd.org/dnd/images/white-dragon.jpg',
  'Yuan-ti Abomination':
    'https://www.aidedd.org/dnd/images/yuan-ti-abomination.jpg',
  'Yuan-ti Malison': 'https://www.aidedd.org/dnd/images/yuan-ti-malison.jpg',
  'Yuan-ti Pureblood':
    'https://www.aidedd.org/dnd/images/yuan-ti-pureblood.jpg',
  Zombie: 'https://www.aidedd.org/dnd/images/zombie.jpg',
};
