export const NPC_MOOD = [
  'Agradable',
  'Despreocupado',
  'Curioso',
  'Ansioso',
  'Amigable',
  'Alegre',
  'Esperanzado',
  'Optimista',
  'Indiferente',
  'Aburrido',
  'Concentrado',
  'Sospechoso',
  'Cansado',
  'Ensimismado',
  'Desagradable',
  'Agitado',
  'Enfadado',
  'Abatido',
  'Sombrío',
  'Nervioso',
];

export const NPC_CALM = [
  'Compasiva',
  'Alegre',
  'Reservada',
  'Abierta',
  'Desineteresada',
  'Brusca',
  'Ansiosa',
  'Engañosa',
  'Necia',
  'Estricta',
  'Agradable',
  'Traviesa',
  'Enfadada',
  'Temerosa',
  'Manipulativa',
  'Devota',
  'Ávara',
  'Divertida',
  'Austera',
  'Cariñosa',
  'Vaga',
  'Decidida',
  'Jactanciosa',
  'Artística',
  'Asertiva',
  'Descuidada',
  'Cuidadosa',
  'Segura',
  'Considerada',
  'Leal',
  'Sofisticada',
  'Fácilmente convencible',
];

export const NPC_STRESS = [
  'Retraída',
  'Asesina',
  'Obsesiva',
  'Autoritaria',
  'Determinada',
  'Valiente',
  'Malévola',
  'Beligerante',
  'Cáustica',
  'Temeraria',
  'Discutidora',
  'Sobreprotectora',
  'Enfadada',
  'Cobarde',
  'Meticulosa',
  'Sarcástica',
  'Cabezota',
  'Destructiva',
  'Práctica',
  'Molesta',
  'Fanática',
  'Reservada',
  'Impráctica',
  'Indiferente',
  'Calculadora',
  'Trabajadora',
  'Manipuladora',
  'Compulsiva',
  'Intolerante',
];

export const NPC_PREJUDICES = [
  [null, []],
  ['Género contrario', []],
  ['Un grupo de edad', ['Niños', 'Adolescentes', 'Mayores']],
  [
    'Una clase social',
    [
      'Clase dirigente y figuras autoritarias',
      'Ricos y poderosos',
      'Pobres e indigentes',
    ],
  ],
  ['Inadaptados sociales', ['Mendigos', 'Borrachos', 'Drogadictos']],
  [
    'Una profesión',
    [
      'Granjeros',
      'Artistas',
      'Clero',
      'Soldados',
      'Pescadores',
      'Rameras',
      'Mineros',
      'Mercaderes',
      'Eruditos',
      'Pastores',
      'Marineros',
      'Magos',
    ],
  ],
  [
    'Una raza',
    [
      'Enanos',
      'Elfos',
      'Gnomos',
      'Goblins',
      'Mestizos',
      'Medianos',
      'Humanos',
      'Orcos',
      'Reptilianos',
    ],
  ],
];

export const NPC_FLAWS = [
  'Se agita nervioso',
  'Bebe mucho',
  'Come mucho',
  'Maldice',
  'Higiene pobre',
  'No puede resistirse a flirtear',
  'No puede parar de fijar la mirada',
  'Suda fácil y abundantemente',
  'Mentiroso compulsivo',
  'Adorna la verdad',
  'Exagera detalles',
  'Tiene mal carácter, se enfada fácilmente',
  'Es melodramático',
  'Cotilla',
  'Mastica con la boca abierta',
  'Se cree todo lo que le digas',
  'Escéptico con todo',
  'Deambula constantemente',
  'No sabe mantener la mirada',
  'Enamoradizo',
  'Disfruta de vicios',
  'Arrogante',
  'Envidia posesiones o estatus de alguien',
  'Codicioso',
  'Tiene un enemigo',
  'Pasado avergonzante',
  'Pasado criminal',
  'Posee secretos perdidos',
  'Posee secretos prohibidos',
  'Temerario',
];

export const NPC_EXTREME_ABILITIES = {
  high: [
    'Mucha Fuerza. Musculoso, fuerte como un buey',
    'Mucha Destreza. Ligero, ágil, grácil',
    'Mucha Constitución. Resistente, robusto, sano',
    'Mucha Inteligencia. Estudioso, culto, inquisitivo',
    'Mucha Sabiduría. Perceptivo, intuitivo, perspicaz',
    'Mucho Carisma. Persuasivo, convincente, líder natural',
  ],
  low: [
    'Poca Fuerza. Débil, enclenque',
    'Poca Destreza. Torpe, patoso',
    'Poca Constitución. Lánguido, enfermizo',
    'Poca Inteligencia. Inculto, corto, lento de razonamiento',
    'Poca Sabiduría. Distraído, poco perceptivo',
    'Poco Carisma. Aburrido, apagado',
  ],
};

export const NPC_TALENTS = [
  'Toca un instrumento musical',
  'Habla varios idiomas',
  'Increíblemente suertudo',
  'Memoria perfecta',
  'Se le dan bien los animales',
  'Se le dan bien los niños',
  'Se le dan bien los puzzles',
  'Se le dan bien las imitaciones',
  'Dibuja bien',
  'Pinta bien',
  'Canta bien',
  'Gana a cualquiera bebiendo',
  'Carpintero experto',
  'Cocinero experto',
  'Experto en dardos y lanzar piedras',
  'Malabarista experto',
  'Actor experto y maestro del disfraz',
  'Bailarín experto',
  'Conoce el truco de los ladrones',
];

export const NPC_IDEALS = {
  L: [
    'Comunidad',
    'Justicia',
    'Honor',
    'Lógica',
    'Responsabilidad',
    'Tradición',
    'Nación',
  ],
  C: [
    'Cambio',
    'Creatividad',
    'Libertad',
    'Independencia',
    'Sin límites',
    'Capricho',
  ],
  G: ['Belleza', 'Caridad', 'Bien mayor', 'Vida', 'Respeto', 'Autosacrificio'],
  E: ['Dominación', 'Avaricia', 'Poder', 'Dolor', 'Venganza', 'Matanza'],
  N: [
    'Balance',
    'Conocimiento',
    'Vive y deja vivir',
    'Moderación',
    'Neutralidad',
    'Kandraxianos',
  ],
  O: [
    'Aspiración',
    'Descubrimiento',
    'Gloria',
    'Redención',
    'Conocerse a uno mismo',
  ],
};

export const NPC_BONDS = [
  'Dedicado a un objetivo personal',
  'Protector de su familia cercana',
  'Protector de compañeros y compatriotas',
  'Leal a su benefactor, patrón o empleador',
  'Capturado por su interés romántico',
  'Atado a un lugar especial',
  'Protector de un recuerdo sentimental',
  'Protector de una posesión valiosa',
  'En busca de venganza',
  null,
];
