export const NPC_FAITH_DESCRIPTION = [
  'Verdadero creyente discreto',
  'Practicante casual',
  'Estudiante crítico',
  'Abiertamente cínico',
  'Curioso de mente abierta',
  'Fe perdida',
  'Cauteloso',
  'Verdadero creyente fanático',
];

export const NPC_DEITIES = [
  [35, 'Matter'],
  [20, 'Energy'],
  [10, 'Spirit'],
  [5, 'Space'],
  [30, 'None'],
];

export const NPC_DEITIES_NAMES = {
  Matter: [
    [60, 'Simtu'],
    [40, 'Abnu'],
    [30, 'Sabatu'],
    [20, 'Zid'],
    [10, 'Terrafar'],
    [10, 'Durku'],
    [10, 'Tigris'],
    [10, 'Mummu'],
    [10, 'Ishtar'],
    [10, 'Astar'],
    [10, 'Ashnan'],
  ],
  Energy: [
    [60, 'Akosh'],
    [40, 'Giru'],
    [30, 'Ilu'],
    [20, 'Dshim'],
    [10, 'Nusku'],
    [10, 'Hefesto'],
    [10, 'Kothar'],
  ],
  Spirit: [
    [60, 'Kabattu'],
    [40, 'Lamassu'],
    [30, 'Napsutu'],
    [20, 'Namtar'],
    [10, 'Ayya'],
    [10, 'Shalmu'],
    [10, 'Ishqum'],
    [10, 'Laylu'],
    [10, 'Nabu'],
    [10, 'Dianna'],
  ],
  Space: [
    [60, 'Burumu'],
    [40, 'Alaktu'],
    [30, 'Dumu'],
    [20, 'Nashi’um'],
    [10, 'Shumu'],
    [10, 'Kur'],
    [10, 'Anqamar'],
    [10, 'Shamash'],
    [10, 'Ilmun'],
  ],
  None: [
    [50, 'Indiferente con los dioses'],
    [35, 'Seguidor de todos los dioses'],
    [15, 'Contra todos los dioses'],
  ],
};
