export const NPC_RACES = {
  human: {
    name: 'human',
    translation: 'Humano',
    probabilityWeight: 300,
    names: ['Dragonborn', 'Human', 'Tiefling'],
  },
  dwarf: {
    name: 'dwarf',
    translation: 'Enano',
    probabilityWeight: 60,
    names: ['Dwarf'],
  },
  elf: {
    name: 'elf',
    translation: 'Elfo',
    probabilityWeight: 60,
    names: ['Elf'],
  },
  halfling: {
    name: 'halfling',
    translation: 'Mediano',
    probabilityWeight: 40,
    names: ['Halfling'],
  },
  'half-elf': {
    name: 'half-elf',
    translation: 'Semielfo',
    probabilityWeight: 20,
    names: ['Human', 'Elf'],
  },
  'half-orc': {
    name: 'half-orc',
    translation: 'Semiorco',
    probabilityWeight: 20,
    names: ['Half-Orc', 'Gith', 'Human.Niger-Congo'],
  },
  gnome: {
    name: 'gnome',
    translation: 'Gnomo',
    probabilityWeight: 16,
    names: ['Gnome'],
  },
  orc: {
    name: 'orc',
    translation: 'Orco',
    probabilityWeight: 10,
    names: ['Half-Orc', 'Gith', 'Human.Niger-Congo'],
  },
  goblin: {
    name: 'goblin',
    translation: 'Goblin',
    probabilityWeight: 10,
    names: ['Half-Orc', 'Gith', 'Human.Chinese', 'Human.Slavic'],
  },
  bugbear: {
    name: 'bugbear',
    translation: 'Osgo',
    probabilityWeight: 6,
    names: ['Half-Orc', 'Gith', 'Human.Niger-Congo', 'Human.Slavic'],
  },
  triton: {
    name: 'triton',
    translation: 'Tritón',
    probabilityWeight: 2,
    names: ['Tiefling', 'Gith', 'Human'],
  },
  satyr: {
    name: 'satyr',
    translation: 'Sátiro',
    probabilityWeight: 2,
    names: ['Tiefling', 'Gith', 'Human'],
  },
  lizardfolk: {
    name: 'lizardfolk',
    translation: 'Hombre lagarto',
    probabilityWeight: 2,
    names: ['Lizardfolk'],
  },
  kobold: {
    name: 'kobold',
    translation: 'Kóbold',
    probabilityWeight: 2,
    names: ['Tiefling', 'Gith', 'Half-Orc', 'Human.Indian', 'Human.Slavic'],
  },
  hobgoblin: {
    name: 'hobgoblin',
    translation: 'Hobgoblin',
    probabilityWeight: 2,
    names: [
      'Tiefling',
      'Gith',
      'Half-Orc',
      'Human.Niger-Congo',
      'Human.Slavic',
      'Human.Egyptian',
    ],
  },
  fairy: {
    name: 'fairy',
    translation: 'Hada',
    probabilityWeight: 2,
    names: [
      'Tiefling',
      'Gith',
      'Human.Chinese',
      'Human.Mesoamerican',
      'Human.Japanese',
      'Human.Niger-Congo',
      'Human.Polynesian',
    ],
  },
  changeling: {
    name: 'changeling',
    translation: 'Cambiaformas',
    probabilityWeight: 1,
    names: ['Dragonborn', 'Human', 'Tiefling'],
  },
  minotaur: {
    name: 'minotaur',
    translation: 'Minotauro',
    probabilityWeight: 1,
    names: [
      'Dragonborn',
      'Half-Orc',
      'Tiefling',
      'Gith',
      'Human.Egyptian',
      'Human.Niger-Congo',
      'Human.Greek',
    ],
  },
  centaur: {
    name: 'centaur',
    translation: 'Centauro',
    probabilityWeight: 1,
    names: [
      'Dragonborn',
      'Gith',
      'Tiefling',
      'Human.Egyptian',
      'Human.Niger-Congo',
      'Human.Roman',
      'Human.Greek',
    ],
  },
};

export const NPC_RACES_LIST = Object.keys(NPC_RACES);
